scrolling = { history = 10000 , multiplier = 3}
mouse.hide_when_typing = true
mouse.bindings = [
    {mouse="Right", action="ExpandSelection"},
    {mouse="Right",mods="Control",action="Paste"},
    {mouse="Right", mods="Shift", action="ExpandSelection"}
]


window.padding = { x = 3}

[[keyboard.bindings]]
key="v"
action="ToggleViMode"
mods="Control|Alt"

[font]
normal.family = "FiraCode Nerd Font Propo SemBd"

[font.bold]
family = "FiraCode Nerd Font"
style = "bold"

[colors.primary]
background = "#1b1e30"
foreground = "#c0caf5"

# Normal colors
[colors.normal]
black = "#4b5263"
red = "#ff7e67"
green = "#a8cc8c"
yellow = "#ffcc66"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#d0d7e5"

# Bright colors
[colors.bright]
black = "#676e95"
red = "#ff7e67"
green = "#a8cc8c"
yellow = "#ffcc66"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#d0d7e5"

