scrolling = { history = 10000 , multiplier = 3}
mouse.hide_when_typing = true
mouse.bindings = [
    {mouse="Right", action="ExpandSelection"},
    {mouse="Right",mods="Control",action="Paste"},
]


window.padding = { x = 12, y = 5}

[[keyboard.bindings]]
key="v"
action="ToggleViMode"
mods="Control|Alt"

[font]
normal.family = "FiraCode Nerd Font"
normal.style = "Medium"

[colors.primary]
background = "#24283b"
foreground = "#a9b1d6"


# Normal colors
[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#9699a8"

# Bright colors
[colors.bright]
black = "#444b6a"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7da6ff"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#acb0d0"

